version: '3'
services:
  db:
     image: mysql
     container_name: mysql_db
     restart: always
     environment:
        - MYSQL_ROOT_PASSWORD="vilas@123"
  web:
    image: apache1
    build: ./app2
    depends_on:
       - db
    container_name: apache_web
    restart: always
    ports:
      - "81:80"
